FROM node:18.19
LABEL maintainer="Alejandro Aguilar <emonics.aguilar@gmail.com>"
# RUN mkdir /usr/app/
# RUN mkdir /usr/app/strapi 
# WORKDIR /usr/app/strapi
# RUN npm install
# ARG configuration=development




# RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev git
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

RUN yarn global add node-gyp
RUN yarn config set network-timeout 600000 -g && yarn install
ENV PATH /usr/app/strapi/node_modules/.bin:$PATH

COPY ./projects/strapi ./
WORKDIR /usr/app/strapi
RUN chown -R node:node /usr/app/strapi/dist
USER node
RUN ["yarn", "build"]
EXPOSE 1337
CMD ["yarn", "develop"]

